### ISSUE TITLE
Request: raspberry pi setup guide

### ISSUE THREAD

**Issue by daleanthony** [mkellsy/homebridge-config-ui#11]
Would be awesome if there was a guide to help get this running on raspberry pi. I'm a little out of my depth here so no clue what I'm doing... otherwise I'd offer to do it myself 😂

**Comment by mkellsy** [comment]
Anyone have this running on a PI? I only have tested this on OSX, Fedora and FreeBSD.

**Comment by shidevil** [comment]
It's working on PI. If you have setup homebridge according to https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi

Then it would be the same as installing other plugins.

`sudo npm i -g homebridge-config-ui`

and add the config to config.json either at /var/homebridge/config.json if you are using systemd or at ~/.homebridge/config.json - check readme

**Comment by mkellsy** [comment]
After some research Homebridge runs differently on a PI. Since Homebridge is very popular on PIs, this is worth some research and further documentation.

**Comment by warrenphd** [comment]
+1...would be great to support this on RPI

**Comment by raaffq** [comment]
Any update? Web UI for Raspberry?
