### ISSUE TITLE
AJAX calls are being blocked by ad blockers

### ISSUE THREAD

**Issue by mkellsy** [mkellsy/homebridge-config-ui#13]
Need to change AJAX URLs to pass ad blocker filtering. This will prevent errors like this; net::ERR_BLOCKED_BY_CLIENT

**Comment by shidevil** [comment]
It's blocking due to /scripts/logs.js 

Possible to change the logs location to somewhere else?

**Comment by shidevil** [comment]
@mkellsy All adblocks has filters for /scripts/log.js. I tried changing the scripts to script and it works perfectly.

Would you want me to do a pull request for this?

**Comment by mkellsy** [comment]
This was a CORS issue with the NPM API. Fixed now.
