### ISSUE TITLE
Login impossible

### ISSUE THREAD

**Issue by jenswet** [mkellsy/homebridge-config-ui#15]
Hello,
I just found your plugin and it looks nice.
I just installed it and tried to login. Unfortunately the login does not work. After entering the default credentials it is just endless loading. In the homebridge console I can see "login successful" but it never redirects to the dashboard.
How can I fix this?
And a second question: I use systemd for starting homebridge, so there is no dedicated log file (it uses journalctl), how can I include this log in config? Is this possible yet?
Thanks in advance! Great work!
Cheers,
Jens

**Comment by shidevil** [comment]
Have you tried another browser? Also do remember to turn off Adblock. 

For systemd please read the readme. H
{
    "platform": "config",
    "name": "Config",
    "port": 8080,
    "log": "/var/log/daemon.log",
    "restart": "sudo systemctl restart homebridge.service"
}

**Comment by jenswet** [comment]
I tried Safari (with disabled adblock) and Chrome (without Adblock). Both have the same problem.

I have no /var/log/daemon.log. How can I get the service to output this log? All logs are stored journalctl in /run/log/journal/....

**Comment by shidevil** [comment]
@jenswet That is weird, are you running as systemd? As systemd output the logs to /var/log/daemon.log or /var/log/syslog

Could you check?

**Comment by shidevil** [comment]
@jenswet @cuihaijun If you are running homebridge via systemd.

Head to /var/homebridge and create a auth.json. Try it again? 

[
    {
        "id": 1,
        "username": "admin",
        "password": "admin",
        "name": "Admin",
        "admin": true
    }
]

**Comment by jenswet** [comment]
Hello,
The auth.json was automatically created with the same content on the first start of the plugin. As I said the homebridge console stats successful login, only the redirect does not work. it's endless loading.

Regarding the log: I use a systemd service, but there is no log in /var/log. systemd only saves the log with journald to /run/log/journal/UUID/system.journal

**Comment by shidevil** [comment]
Have you tried putting 

"log": "/run/log/journal/UUID/system.journal"

**Comment by jenswet** [comment]
I will try as soon I am able to login... Any ideas how to fix that before?

**Comment by cuihaijun** [comment]
How can I modify, remove the user name and password, I think it is added password, login, a problem, resulting in not login

**Comment by cuihaijun** [comment]
netstat -na | grep 8080
tcp6       0      0 :::8080                 :::*                    LISTEN
Should it be like this?
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN

**Comment by jenswet** [comment]
volumio@volumio:/var/homebridge$ netstat -na | grep 8080
tcp6       0      0 :::8080                 :::*                    LISTEN     
tcp6       0      0 192.168.178.33:8080     192.168.178.36:63941    ESTABLISHED

The login page loads fine. When I type a wrong password the login Form gets reset. When I type the correct credentials it starts loading and never finishes.
Console states:
Aug 02 06:54:18 volumio homebridge[14336]: [8/2/2017, 6:54:18 AM] [Config] Administrator successfully logged in.

**Comment by shidevil** [comment]
have never experience if before. Have you tried to run in debug mode to see the problem? 

sudo DEBUG=* homebridge -D

https://github.com/nfarina/homebridge/wiki/Basic-Trouble-Shooting

**Comment by jenswet** [comment]
This is the output starting from loading the login page. After clicking login nothing happens in browser (endless loading) and nothing happens in log.


EventedHTTPServer [::ffff:192.168.178.27] HTTP Response is finished +2ms
/  express:router dispatching GET / +28s
  express:router query  : / +13ms
  express:router expressInit  : / +5ms
  express:router serveStatic  : / +4ms
  send stat "/lib/node_modules/homebridge-config-ui/public/index.html" +0ms
  express:router cookieParser  : / +32ms
  express:router urlencodedParser  : / +8ms
  body-parser:urlencoded skip empty body +0ms
  express:router session  : / +8ms
  express-session fetching EHo3SDMHxg2T3bOa96y3V56hX0ay0PXr +0ms
  express:router dispatching GET /styles/layout.css +21ms
  express:router query  : /styles/layout.css +2ms
  express:router expressInit  : /styles/layout.css +2ms
  express:router serveStatic  : /styles/layout.css +3ms
  send stat "/lib/node_modules/homebridge-config-ui/public/styles/layout.css" +63ms
  express:router dispatching GET /styles/fonts.css +8ms
  express:router query  : /styles/fonts.css +2ms
  express:router expressInit  : /styles/fonts.css +3ms
  express:router serveStatic  : /styles/fonts.css +3ms
  send stat "/lib/node_modules/homebridge-config-ui/public/styles/fonts.css" +14ms
  express:router dispatching GET /scripts/jquery.min.js +6ms
  express:router query  : /scripts/jquery.min.js +2ms
  express:router expressInit  : /scripts/jquery.min.js +1ms
  express:router serveStatic  : /scripts/jquery.min.js +1ms
  send stat "/lib/node_modules/homebridge-config-ui/public/scripts/jquery.min.js" +11ms
  express-session no session found +45ms
  express:router initialize  : / +23ms
  express:router authenticate  : / +2ms
  express:router router  : / +7ms
  express:router dispatching GET / +2ms
  express-session saving jFc3dTdvs7dl7Wpdtnu4BXvhAqL8hsij +79ms
  express-session split response +3ms
  express-session set-cookie connect.sid=s%3AjFc3dTdvs7dl7Wpdtnu4BXvhAqL8hsij.GTpQ%2BqvC63J8TgZw2VxXSbKKFaMbbFgy6oPorE2XjGg; Path=/; HttpOnly +13ms
  send pipe "/lib/node_modules/homebridge-config-ui/public/styles/layout.css" +107ms
  send accept ranges +2ms
  send cache-control public, max-age=0 +2ms
  send modified Sat, 22 Jul 2017 22:03:10 GMT +1ms
  send etag W/"239f-15d6c536130" +4ms
  send content-type text/css +1ms
  send not modified +7ms
  send pipe "/lib/node_modules/homebridge-config-ui/public/styles/fonts.css" +6ms
  send accept ranges +1ms
  send cache-control public, max-age=0 +1ms
  send modified Fri, 21 Jul 2017 12:59:28 GMT +0ms
  send etag W/"240-15d653b3f80" +1ms
  send content-type text/css +1ms
  send not modified +1ms
  send pipe "/lib/node_modules/homebridge-config-ui/public/scripts/jquery.min.js" +4ms
  send accept ranges +1ms
  send cache-control public, max-age=0 +0ms
  send modified Fri, 21 Jul 2017 12:59:28 GMT +1ms
  send etag W/"15283-15d653b3f80" +0ms
  send content-type application/javascript +1ms
  send not modified +1ms
  express:router dispatching GET /styles/material.css +123ms
  express:router query  : /styles/material.css +0ms
  express:router expressInit  : /styles/material.css +1ms
  express:router serveStatic  : /styles/material.css +2ms
  send stat "/lib/node_modules/homebridge-config-ui/public/styles/material.css" +15ms
  express:router dispatching GET /images/snapshot.jpg +3ms
  express:router query  : /images/snapshot.jpg +1ms
  express:router expressInit  : /images/snapshot.jpg +0ms
  express:router serveStatic  : /images/snapshot.jpg +1ms
  send stat "/lib/node_modules/homebridge-config-ui/public/images/snapshot.jpg" +5ms
  express:router dispatching GET /login +3ms
  express:router query  : /login +1ms
  express:router expressInit  : /login +1ms
  express:router serveStatic  : /login +1ms
  send stat "/lib/node_modules/homebridge-config-ui/public/login" +6ms
  send pipe "/lib/node_modules/homebridge-config-ui/public/styles/material.css" +1ms
  send accept ranges +0ms
  send cache-control public, max-age=0 +1ms
  send modified Fri, 21 Jul 2017 12:59:28 GMT +1ms
  send etag W/"514c3-15d653b3f80" +0ms
  send content-type text/css +1ms
  send not modified +1ms
  send pipe "/lib/node_modules/homebridge-config-ui/public/images/snapshot.jpg" +2ms
  send accept ranges +0ms
  send cache-control public, max-age=0 +1ms
  send modified Fri, 21 Jul 2017 12:59:28 GMT +0ms
  send etag W/"2981f-15d653b3f80" +1ms
  send content-type image/jpeg +0ms
  send not modified +1ms
  express:router cookieParser  : /login +15ms
  express:router urlencodedParser  : /login +2ms
  body-parser:urlencoded skip empty body +245ms
  express:router session  : /login +2ms
  express-session fetching jFc3dTdvs7dl7Wpdtnu4BXvhAqL8hsij +92ms
  express-session session found +1ms
  express:router initialize  : /login +6ms
  express:router authenticate  : /login +1ms
  express:router router  : /login +3ms
  express:router dispatching GET /login +1ms
  express:view lookup "login.html" +9ms
  express:view stat "/lib/node_modules/homebridge-config-ui/views/login.html" +2ms
  express:view render "/lib/node_modules/homebridge-config-ui/views/login.html" +5ms
  express:router dispatching GET /scripts/material.web.min.js +76ms
  express:router query  : /scripts/material.web.min.js +1ms
  express:router expressInit  : /scripts/material.web.min.js +0ms
  express:router serveStatic  : /scripts/material.web.min.js +1ms
  send stat "/lib/node_modules/homebridge-config-ui/public/scripts/material.web.min.js" +114ms
  send pipe "/lib/node_modules/homebridge-config-ui/public/scripts/material.web.min.js" +4ms
  send accept ranges +0ms
  send cache-control public, max-age=0 +1ms
  send modified Fri, 21 Jul 2017 12:59:28 GMT +0ms
  send etag W/"2fab6-15d653b3f80" +1ms
  send content-type application/javascript +0ms
  send not modified +1ms
  express-session touching +217ms
  express-session split response +3ms
  express-session touched +7ms
  express:router dispatching POST /login +10s
  express:router query  : /login +0ms
  express:router expressInit  : /login +1ms
  express:router serveStatic  : /login +1ms
  express:router cookieParser  : /login +0ms
  express:router urlencodedParser  : /login +1ms
  body-parser:urlencoded content-type "application/x-www-form-urlencoded" +11s
  body-parser:urlencoded content-encoding "identity" +17ms
  body-parser:urlencoded read body +0ms
  body-parser:urlencoded parse body +123ms
  body-parser:urlencoded parse extended urlencoding +2ms
  express:router session  : /login +155ms
  express-session fetching jFc3dTdvs7dl7Wpdtnu4BXvhAqL8hsij +10s
  express-session session found +1ms
  express:router initialize  : /login +4ms
  express:router authenticate  : /login +1ms
  express:router router  : /login +1ms
  express:router dispatching POST /login +1ms
[8/2/2017, 7:57:41 AM] [Config] Administrator successfully logged in.
  express-session saving jFc3dTdvs7dl7Wpdtnu4BXvhAqL8hsij +22ms
  express-session split response +2ms
  express:router dispatching GET / +45ms
  express:router query  : / +1ms
  express:router expressInit  : / +1ms
  express:router serveStatic  : / +0ms
  send stat "/lib/node_modules/homebridge-config-ui/public/index.html" +11s
  express:router cookieParser  : / +7ms
  express:router urlencodedParser  : / +1ms
  body-parser:urlencoded skip empty body +74ms
  express:router session  : / +0ms
  express-session fetching jFc3dTdvs7dl7Wpdtnu4BXvhAqL8hsij +36ms
  express-session session found +1ms
  express:router initialize  : / +4ms
  express:router authenticate  : / +1ms
  express:router router  : / +7ms
  express:router dispatching GET / +0ms

Any ideas? Anything I can provide you to get this running?

**Comment by shidevil** [comment]
Got to wait for @mkellsy to check on it.

**Comment by FlottoDe** [comment]
Hi,

I'm facing the exact same Problem. Would really appreciate a solution since the plugin looks really awesome! If there is anythin I can provide you with, let me know!

**Comment by Krocko** [comment]
Have an similar problem since yesterday. Got the following error
```
Aug 05 09:35:44 raspberrypi homebridge[1599]: [2017-8-5 09:35:44] [Homebridge Konfiguration] Administrator successfully logged in.
Aug 05 09:35:44 raspberrypi homebridge[1599]: /usr/local/lib/node_modules/homebridge-config-ui/npm.js:135
Aug 05 09:35:44 raspberrypi homebridge[1599]: var desc = body.collected.metadata.description.replace(/(?:https?|ftp):\/\/[\n\S]+/g, "").trim();
Aug 05 09:35:44 raspberrypi homebridge[1599]: ^
Aug 05 09:35:44 raspberrypi homebridge[1599]: TypeError: Cannot read property 'metadata' of undefined
Aug 05 09:35:44 raspberrypi homebridge[1599]: at Request._callback (/usr/local/lib/node_modules/homebridge-config-ui/npm.js:135:50)
Aug 05 09:35:44 raspberrypi homebridge[1599]: at Request.self.callback (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/request/request.js:188:22)
Aug 05 09:35:44 raspberrypi homebridge[1599]: at emitTwo (events.js:125:13)
Aug 05 09:35:44 raspberrypi homebridge[1599]: at Request.emit (events.js:213:7)
Aug 05 09:35:44 raspberrypi homebridge[1599]: at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/request/request.js:1171:10)
Aug 05 09:35:44 raspberrypi homebridge[1599]: at emitOne (events.js:115:13)
Aug 05 09:35:44 raspberrypi homebridge[1599]: at Request.emit (events.js:210:7)
Aug 05 09:35:44 raspberrypi homebridge[1599]: at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/request/request.js:1091:12)
Aug 05 09:35:44 raspberrypi homebridge[1599]: at Object.onceWrapper (events.js:314:30)
Aug 05 09:35:44 raspberrypi homebridge[1599]: at emitNone (events.js:110:20)
Aug 05 09:35:44 raspberrypi homebridge[1599]: at IncomingMessage.emit (events.js:207:7)
Aug 05 09:35:44 raspberrypi homebridge[1599]: at endReadableNT (_stream_readable.js:1045:12)
Aug 05 09:35:44 raspberrypi homebridge[1599]: at _combinedTickCallback (internal/process/next_tick.js:138:11)
Aug 05 09:35:44 raspberrypi homebridge[1599]: at process._tickCallback (internal/process/next_tick.js:180:9)
```
Until yesterday everything working.

**Comment by mkellsy** [comment]
This looks like an issue with getting the status of the homebridge package. I will need some error handling around this, because it looks like the npm api can be down from time to time.

**Comment by edgariscoding** [comment]
Just want to share that I've been having this issue as well. I'm kind of glad to see that it's not just an error with my configuration.

**Comment by shidevil** [comment]
Okay, i am able to replicate this issue if and only if there is no internet. Some users may have npm api down from time to time. As it is checking homebridge version upon login. 

I am pulling a new request for this issue.

**Comment by shidevil** [comment]
Fix for login is done. User can edit npm.js at node_modules/homebridge-config-ui/ 

Check the pull request for the npm.js file

**Comment by AKWillows** [comment]
Hi, I've just installed this plug-on and I, too, can't get past the login screen... it just continues to try loading. I have used safari and Chrome with ad blockers turned off

**Comment by shidevil** [comment]
@AKWillows please check the pull request. you can fix it in the npm.js

**Comment by shidevil** [comment]
@AKWillows https://github.com/mkellsy/homebridge-config-ui/pull/17/commits/6856a9bcf4f8d562e4bb7f3620f69ac00f0ec333

Look at this.

**Comment by AKWillows** [comment]
@shidevil thanks - will take a look in more detail later - not done anything like that before but will give it a go! (backing file first! LOL)

**Comment by shidevil** [comment]
@AKWillows Do try it out. It should work 👍

**Comment by Krocko** [comment]
@AKWillows: simply install @shidevil‘s Fork. 😉
`sudo chown -R $USER /usr/local && npm install -g https://github.com/shidevil/homebridge-config-ui`

**Comment by AKWillows** [comment]
@shidevil @Krocko Afraid i tried both of these solutions but I still just get the progress bar sticking after entering credentials. I think I must be doing something stupid... @Krocko How do I uninstall the plug-in now I have used your method? is it the same sudo uninstall -g homebridge-config-ui ?

**Comment by Krocko** [comment]
Yes it is the same command `sudo npm uninstall -g homebridge-config-ui`

**Comment by shidevil** [comment]
@AKwillows have you restart homebridge after saving the npm file? Please post the log thank you.

**Comment by shidevil** [comment]
Do remember to restart homebridge after doing any changes.

**Comment by shidevil** [comment]
@Krocko Is my pull request working for you on this login issue? 

@jenswet @edgariscoding @cuihaijun Could you guys check as well?

**Comment by Krocko** [comment]
@shidevil no problems with login anymore.

**Comment by cuihaijun** [comment]
@shidevil still can't log in

**Comment by shidevil** [comment]
@cuihaijun did you change the npm on my fork? Could you show me ur debug log if possible. Thanks

**Comment by shidevil** [comment]
@cuihaijun please restart homebridge after you make the changes.

**Comment by cuihaijun** [comment]
@shidevil when I replace /usr/local/lib/ with  /usr/lib/ in npm.js, I work fine,command:which homebrdige,show usr/local/bin/homebridge

**Comment by shidevil** [comment]
No. U need to go to node_modules to change the npm.js 

Please search at usr/local/lib/node_modules/homebridge-config-ui 

Or usr/lib/node_modules/homebridge-config-ui

The npm.js is in that folder

**Comment by cuihaijun** [comment]
The npm.js is in usr/local/lib/node_modules/homebridge-config-ui folder

**Comment by shidevil** [comment]
Yes. could you replace that and restart homebridge. 

If can't login please post debug log. Thanks

**Comment by cuihaijun** [comment]
thanks 
the reason is that homebridge in installed in the usr/local/bin/homebridge folder

**Comment by shidevil** [comment]
Shouldn't matter if homebridge is installed at usr/local/bin/homebridge 

Best of you could provide the debug log.

**Comment by shidevil** [comment]
@cuihaijun you can post the debug log and I will look at it. Thank you so much.

**Comment by AKWillows** [comment]
Hi @shidevil I will re-install and try one more time this afternoon if i have time. I did edit the  npm.js file and restarted home bridge but it still didn't work for me. If I do get a chance (stupid question coming up...) where will I find the debug log?

**Comment by shidevil** [comment]
@AKWillows sudo DEBUG=* homebridge -D

Make sure that ur ~/.homebridge/config.json have the platform

**Comment by cuihaijun** [comment]
@shidevil

**Comment by shidevil** [comment]
@cuihaijun Thanks will take a look.

**Comment by shidevil** [comment]
@cuihaijun saw the log, indeed there is some abnormality in the log but i was not able to verify what causes it. 

1) could you test by changing port to 8080? 
2) off any plugins on ur web browser. eg. adblocks etc.

**Comment by AKWillows** [comment]
HI @shidevil I have reinstalled, amended the npm.js file with the different lines at line 135, added the config.sys and rebooted the RaspberryPi before attempting to open the config webpage in my browser. I can confirm adblocker its urned off. Log file is attached (not sure how much to include!)
[Logfile.txt](https://github.com/mkellsy/homebridge-config-ui/files/1257287/Logfile.txt)

**Comment by shidevil** [comment]
@AKWillows thanks will look into it as well. Did u change npm.js from line 135? Like everything different :) 

Thanks

**Comment by AKWillows** [comment]
@shidevil I took out the lines 135-148 (those in red on the link you gave me) and replaced them with the new 135 - 156 (those in green on the link)

**Comment by mripponbrown** [comment]
Hi all, very same issue here. I've changed npm.js (even though the internet connection is working fine) and verified the stuff about any adblocker or browser plugin. Apparently the log, in debug mode, also in my case says that login was successful!
I have to say that I started to try on a different port (8082) as 8080 was busy with another plugin (Domoticz), but I've tried also on the standard 8080, temporarily disabling Domoticz and leaving Config-UI running alone. No luck :(

**Comment by RienduPre** [comment]
Hi,

Same issue here, tried everything written before. Tried Safari, CHrome and the RPI builtin browser Chromium. please help, because this seems like a nice plugin

Thanks,
Rien

**Comment by RienduPre** [comment]
Anyone solved this ?????

**Comment by Bankaifan** [comment]
I investigated this a little bit more... 

I do not append another log file, since mine looks the same compared to the others postet above...

The first thing if have seen is, that there is a path 
`send stat "/lib/node_modules/homebridge-config-ui/public/index.html" +0ms`
But there is no index.html. So the next thing I tried was to enter "localhost:8080/index.html" instead of "localhost:8080" (after clicking login once to authenticate) and voila ... i entered the HB-Config interface but get an 404 error with this error:

>  Error: Not Found
>     at /usr/local/lib/node_modules/homebridge-config-ui/app.js:81:15
>     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:317:13)
>     at /usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:284:7
>     at Function.process_params (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:335:12)
>     at next (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:275:10)
>     at /usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:635:15
>     at next (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:260:14)
>     at Function.handle (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:174:3)
>     at router (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:47:12)
>     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:317:13)
>     at /usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:284:7
>     at Function.process_params (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:335:12)
>     at next (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:275:10)
>     at SessionStrategy.strategy.pass (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/passport/lib/middleware/authenticate.js:325:9)
>     at /usr/local/lib/node_modules/homebridge-config-ui/node_modules/passport/lib/strategies/session.js:65:12
>     at pass (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/passport/lib/authenticator.js:327:31)
>     at deserialized (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/passport/lib/authenticator.js:339:7)
>     at /usr/local/lib/node_modules/homebridge-config-ui/app.js:61:9
>     at /usr/local/lib/node_modules/homebridge-config-ui/users.js:6:13
>     at _combinedTickCallback (internal/process/next_tick.js:131:7)
>     at process._tickCallback (internal/process/next_tick.js:180:9)

I looked around a little bit and saw, the only to buttons available are those two on the upper left side.

One with an Mouse-Over-Text "Status" one with "Logs". When I click Status i get the endless running loading button like when i click logon - so the problem seems to be the status-site.
Now i click "Logs" aaaaand the log appears and three other buttons are visible - "Accounts", "Plugins" and "Configuration". 
I tried all of them - they all work great - at the first view. 
I found another problem - giving an user admin-privileges does not work. He keeps being an user.

Since my web programmer time is long gone i can't and don't want to investigate the problems with the Status-page any further but this might help @shidevil or @mkellsy.

**Comment by shidevil** [comment]
guys please try the latest pull request to see if the problem is fix thanks to @RienduPre

**Comment by jenswet** [comment]
Hello,
sorry for the late response. I just applied the patch of your whole pull request. It did not work directly. I could fix it by adding another base path to npm.js: My node_modules is located in "/lib/node_modules". Now its working.
I am using the nodejs preinstalled in Volumio 2.0 OS. It uses the different path specified above.
Thanks for helping me find this and all your other fixes!

**Comment by shidevil** [comment]
@jenswet thanks. I will be updating it to specify the node_modules location.

**Comment by shidevil** [comment]
@jenswet I have updated the my pull request so that you can specify your base path in config :)

**Comment by jenswet** [comment]
Nice addition! This will fix it for all likely and unlikely installation parameters.

I had some errors during saving config before and the auto restart of the service did not work. When I continue my Homekit installation and the errors persist, I'll start a new issue with the details.

**Comment by shidevil** [comment]
@jenswet please open a new issue. Thank you.
