### ISSUE TITLE
Logs takes sometime to load

### ISSUE THREAD

**Issue by shidevil** [mkellsy/homebridge-config-ui#2]
Managed to install this plugin perfectly.

The only issue would be that the logs are taking too long to load on safari.

Great job! thank you

**Comment by mkellsy** [comment]
Currently the log is refreshed with an ajax call. The entire log is loaded every time.

I will be changing this to use sockets and stream the log to the browser. This should fix your slow load times.

**Comment by shidevil** [comment]
Great! thank you!
