### ISSUE TITLE
Error Log

### ISSUE THREAD

**Issue by Sonsi79** [mkellsy/homebridge-config-ui#22]
Hi. Since installation i get the following error in home bridge error log, but config-ui still works.
After few hours Homebridge crash with 100% Memory Usage

> Tue, 26 Sep 2017 20:42:16 GMT send etag W/"239f-15d6c536130"
> Tue, 26 Sep 2017 20:42:16 GMT send content-type text/css
> Tue, 26 Sep 2017 20:42:16 GMT send not modified
> Tue, 26 Sep 2017 20:42:16 GMT send pipe "/usr/lib/node_modules/homebridge-config-ui/public/styles/material.css"
> Tue, 26 Sep 2017 20:42:16 GMT send accept ranges
> Tue, 26 Sep 2017 20:42:16 GMT send cache-control public, max-age=0
> Tue, 26 Sep 2017 20:42:16 GMT send modified Fri, 21 Jul 2017 12:59:28 GMT
> Tue, 26 Sep 2017 20:42:16 GMT send etag W/"514c3-15d653b3f80"
> Tue, 26 Sep 2017 20:42:16 GMT send content-type text/css
> Tue, 26 Sep 2017 20:42:16 GMT send not modified
> Tue, 26 Sep 2017 20:42:16 GMT express:router dispatching GET /scripts/jquery.min.js
> Tue, 26 Sep 2017 20:42:16 GMT express:router query  : /scripts/jquery.min.js
> Tue, 26 Sep 2017 20:42:16 GMT express:router expressInit  : /scripts/jquery.min.js
> Tue, 26 Sep 2017 20:42:16 GMT express:router serveStatic  : /scripts/jquery.min.js
> Tue, 26 Sep 2017 20:42:16 GMT send stat "/usr/lib/node_modules/homebridge-config-ui/public/scripts/jquery.min.js"
> Tue, 26 Sep 2017 20:42:16 GMT express:router dispatching GET /scripts/material.web.min.js
> Tue, 26 Sep 2017 20:42:16 GMT express:router query  : /scripts/material.web.min.js
> Tue, 26 Sep 2017 20:42:16 GMT express:router expressInit  : /scripts/material.web.min.js
> Tue, 26 Sep 2017 20:42:16 GMT express:router serveStatic  : /scripts/material.web.min.js
> Tue, 26 Sep 2017 20:42:16 GMT send stat "/usr/lib/node_modules/homebridge-config-ui/public/scripts/material.web.min.js"
> Tue, 26 Sep 2017 20:42:16 GMT send pipe "/usr/lib/node_modules/homebridge-config-ui/public/scripts/jquery.min.js"
> Tue, 26 Sep 2017 20:42:16 GMT send accept ranges
> Tue, 26 Sep 2017 20:42:16 GMT send cache-control public, max-age=0
> Tue, 26 Sep 2017 20:42:16 GMT send modified Fri, 21 Jul 2017 12:59:28 GMT
> Tue, 26 Sep 2017 20:42:16 GMT send etag W/"15283-15d653b3f80"
> Tue, 26 Sep 2017 20:42:16 GMT send content-type application/javascript
> Tue, 26 Sep 2017 20:42:16 GMT send not modified
> Tue, 26 Sep 2017 20:42:16 GMT send pipe "/usr/lib/node_modules/homebridge-config-ui/public/scripts/material.web.min.js"
> Tue, 26 Sep 2017 20:42:16 GMT send accept ranges
> Tue, 26 Sep 2017 20:42:16 GMT send cache-control public, max-age=0
> Tue, 26 Sep 2017 20:42:16 GMT send modified Fri, 21 Jul 2017 12:59:28 GMT
> Tue, 26 Sep 2017 20:42:16 GMT send etag W/"2fab6-15d653b3f80"
> Tue, 26 Sep 2017 20:42:16 GMT send content-type application/javascript
> Tue, 26 Sep 2017 20:42:16 GMT send not modified
> Tue, 26 Sep 2017 20:42:16 GMT express:router dispatching GET /scripts/log.js
> Tue, 26 Sep 2017 20:42:16 GMT express:router query  : /scripts/log.js
> Tue, 26 Sep 2017 20:42:16 GMT express:router expressInit  : /scripts/log.js
> Tue, 26 Sep 2017 20:42:16 GMT express:router serveStatic  : /scripts/log.js
> Tue, 26 Sep 2017 20:42:16 GMT send stat "/usr/lib/node_modules/homebridge-config-ui/public/scripts/log.js"
> Tue, 26 Sep 2017 20:42:16 GMT send pipe "/usr/lib/node_modules/homebridge-config-ui/public/scripts/log.js"
> Tue, 26 Sep 2017 20:42:16 GMT send accept ranges
> Tue, 26 Sep 2017 20:42:16 GMT send cache-control public, max-age=0
> Tue, 26 Sep 2017 20:42:16 GMT send modified Sat, 22 Jul 2017 22:03:10 GMT
> Tue, 26 Sep 2017 20:42:16 GMT send etag W/"601-15d6c536130"
> Tue, 26 Sep 2017 20:42:16 GMT send content-type application/javascript
> Tue, 26 Sep 2017 20:42:16 GMT send not modified
> Tue, 26 Sep 2017 20:42:16 GMT express:router dispatching GET /scripts/layout.js
> Tue, 26 Sep 2017 20:42:16 GMT express:router query  : /scripts/layout.js
> Tue, 26 Sep 2017 20:42:16 GMT express:router expressInit  : /scripts/layout.js
> Tue, 26 Sep 2017 20:42:16 GMT express:router serveStatic  : /scripts/layout.js
> Tue, 26 Sep 2017 20:42:16 GMT send stat "/usr/lib/node_modules/homebridge-config-ui/public/scripts/layout.js"
> Tue, 26 Sep 2017 20:42:16 GMT send pipe "/usr/lib/node_modules/homebridge-config-ui/public/scripts/layout.js"
> Tue, 26 Sep 2017 20:42:16 GMT send accept ranges
> Tue, 26 Sep 2017 20:42:16 GMT send cache-control public, max-age=0
> Tue, 26 Sep 2017 20:42:16 GMT send modified Fri, 21 Jul 2017 12:59:28 GMT
> Tue, 26 Sep 2017 20:42:16 GMT send etag W/"59e-15d653b3f80"
> Tue, 26 Sep 2017 20:42:16 GMT send content-type application/javascript
> Tue, 26 Sep 2017 20:42:16 GMT send not modified
> Tue, 26 Sep 2017 20:42:16 GMT express:router dispatching GET /styles/fonts.css
> Tue, 26 Sep 2017 20:42:16 GMT express:router query  : /styles/fonts.css
> Tue, 26 Sep 2017 20:42:16 GMT express:router expressInit  : /styles/fonts.css
> Tue, 26 Sep 2017 20:42:16 GMT express:router serveStatic  : /styles/fonts.css
> Tue, 26 Sep 2017 20:42:16 GMT send stat "/usr/lib/node_modules/homebridge-config-ui/public/styles/fonts.css"
> Tue, 26 Sep 2017 20:42:16 GMT send pipe "/usr/lib/node_modules/homebridge-config-ui/public/styles/fonts.css"
> Tue, 26 Sep 2017 20:42:16 GMT send accept ranges
> Tue, 26 Sep 2017 20:42:16 GMT send cache-control public, max-age=0
> Tue, 26 Sep 2017 20:42:16 GMT send modified Fri, 21 Jul 2017 12:59:28 GMT
> Tue, 26 Sep 2017 20:42:16 GMT send etag W/"240-15d653b3f80"
> Tue, 26 Sep 2017 20:42:16 GMT send content-type text/css
> Tue, 26 Sep 2017 20:42:16 GMT send not modified
> Tue, 26 Sep 2017 20:42:16 GMT express:router dispatching GET /fonts/material.woff
> Tue, 26 Sep 2017 20:42:16 GMT express:router query  : /fonts/material.woff
> Tue, 26 Sep 2017 20:42:16 GMT express:router expressInit  : /fonts/material.woff
> Tue, 26 Sep 2017 20:42:16 GMT express:router serveStatic  : /fonts/material.woff
> Tue, 26 Sep 2017 20:42:16 GMT send stat "/usr/lib/node_modules/homebridge-config-ui/public/fonts/material.woff"
> Tue, 26 Sep 2017 20:42:16 GMT send pipe "/usr/lib/node_modules/homebridge-config-ui/public/fonts/material.woff"
> Tue, 26 Sep 2017 20:42:16 GMT send accept ranges
> Tue, 26 Sep 2017 20:42:16 GMT send cache-control public, max-age=0
> Tue, 26 Sep 2017 20:42:16 GMT send modified Fri, 21 Jul 2017 12:59:27 GMT
> Tue, 26 Sep 2017 20:42:16 GMT send etag W/"b9d8-15d653b3b98"
> Tue, 26 Sep 2017 20:42:16 GMT send content-type application/font-woff
> Tue, 26 Sep 2017 20:42:16 GMT send not modified
> Tue, 26 Sep 2017 20:42:16 GMT express:router dispatching GET /log/raw/error
> Tue, 26 Sep 2017 20:42:16 GMT express:router query  : /log/raw/error
> Tue, 26 Sep 2017 20:42:16 GMT express:router expressInit  : /log/raw/error
> Tue, 26 Sep 2017 20:42:16 GMT express:router serveStatic  : /log/raw/error
> Tue, 26 Sep 2017 20:42:16 GMT send stat "/usr/lib/node_modules/homebridge-config-ui/public/log/raw/error"
> Tue, 26 Sep 2017 20:42:16 GMT express:router cookieParser  : /log/raw/error
> Tue, 26 Sep 2017 20:42:16 GMT express:router urlencodedParser  : /log/raw/error
> Tue, 26 Sep 2017 20:42:16 GMT body-parser:urlencoded skip empty body
> Tue, 26 Sep 2017 20:42:16 GMT express:router session  : /log/raw/error
> Tue, 26 Sep 2017 20:42:16 GMT express-session fetching WqbJCy1qPfQ94MQxgIOqjOL9FyBJJOJa
> Tue, 26 Sep 2017 20:42:16 GMT express-session session found
> Tue, 26 Sep 2017 20:42:16 GMT express:router initialize  : /log/raw/error
> Tue, 26 Sep 2017 20:42:16 GMT express:router authenticate  : /log/raw/error
> Tue, 26 Sep 2017 20:42:16 GMT express:router router  : /log/raw/error
> Tue, 26 Sep 2017 20:42:16 GMT express:router dispatching GET /log/raw/error
> Tue, 26 Sep 2017 20:42:16 GMT express:router trim prefix (/log) from url /log/raw/error
> Tue, 26 Sep 2017 20:42:16 GMT express:router router /log : /log/raw/error
> Tue, 26 Sep 2017 20:42:16 GMT express:router dispatching GET /raw/error

**Comment by shidevil** [comment]
@Sonsi79 what other plugins did u install?
