### ISSUE TITLE
Clarify config.json documentation

### ISSUE THREAD

**Issue by ttww** [mkellsy/homebridge-config-ui#23]
For someone new to this kind of configuration, please change the config.json example to so something like this:

> Add this to the **platforms** part of the config.json, eg. for a minimal config without other platforms:
`  "platforms": [`
`    {`
`      "platform": "config",`
`      "name": "Config",`
`      "port": 8080,`
`      "log": "/tmp/daemon.log",`
`      "restart": "sudo systemctl restart homebridge.service"`
`    }`
`  ]`
>
or something like that...
It would save some time for newbies :-)

**Comment by shidevil** [comment]
Hi i have updated this. Thank you

**Comment by ttww** [comment]
Hi,
thanks, but I see no changes  in the documentation :-):

![misleading_config](https://user-images.githubusercontent.com/3983391/31164735-ac11c2fa-a8e8-11e7-935a-bb7f4a8855d1.png)

**Comment by shidevil** [comment]
Hi @ttww please check pull request.

**Comment by shidevil** [comment]
As i am waiting for @mkellsy to push to the main repo. :)
