### ISSUE TITLE
Log is empty and config throws javascript errors

### ISSUE THREAD

**Issue by dmcgrew** [mkellsy/homebridge-config-ui#26]
I am running as systemd but get an empty log and also some errors on the config page. The homepage shows up fine though. Here are the errors on the config page...

`TypeError: Cannot read property 'length' of undefined
    at write (/usr/local/lib/node_modules/homebridge-config-ui/routes/config.js:115:43)
    at /usr/local/lib/node_modules/homebridge-config-ui/routes/config.js:13:5
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/route.js:137:13)
    at /usr/local/lib/node_modules/homebridge-config-ui/routes/config.js:7:9
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:281:22`

**Comment by shidevil** [comment]
Are u using my pull request or the original masters?

**Comment by dmcgrew** [comment]
Using the original master.

**Comment by shidevil** [comment]
@dmcgrew Will take a look.

**Comment by shidevil** [comment]
@dmcgrew could you try to use my pull request to see if its working? thanks

**Comment by dmcgrew** [comment]
I’m a little new to this.. what command should I use to install from a pull request?

**Comment by shidevil** [comment]
@dmcgrew just download my project. Unzip to ur raspberry pi documents folder. Cd into the project documents and do sudo npm -g install

**Comment by dmcgrew** [comment]
Ok thanks. I have your project installed now but still having the same issues. Just to verify, I did remove the previous installation before installing your's.

**Comment by shidevil** [comment]
@dmcgrew what node version and npm version are u using? thank you

**Comment by dmcgrew** [comment]
Node is 4.0 and npm is 2.14.2

**Comment by shidevil** [comment]
@dmcgrew 1) could you take a screen shot of the error at the place it happens?
2) post ur config.json

**Comment by dmcgrew** [comment]
1. Yeah its on the /config page. Sometimes I also get a 500 error. 
<img width="1352" alt="screen shot 2017-10-31 at 12 20 07 pm" src="https://user-images.githubusercontent.com/1474983/32235446-e11c8716-be35-11e7-82dd-86171e72abba.png">

2. Here's the config.json..

`{  
   "bridge":{  
      "name":"Homebridge",
      "username":"CC:22:3D:E3:CE:30",
      "port":51826,
      "pin":"024-48-988"
   },
   "description":"This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
   "platforms":[  
      {  
         "platform":"WeatherStation",
         "name":"Weather Station",
         "key":"2543ca3ae5ac26e0",
         "location":"pws:KPAMARS2",
         "forecast":"3days"
      },
      {  
         "platform":"config",
         "name":"Config",
         "port":8080,
         "log":"/var/log/daemon.log",
         "restart":"sudo systemctl restart homebridge.service"
      }
   ]
}`

**Comment by shidevil** [comment]
Please try this and if you are using my pull request. Please add the base path. 

{  
   "bridge":{  
      "name":"Homebridge",
      "username":"CC:22:3D:E3:CE:30",
      "port":51826,
      "pin":"xxx-xx-xxx"
   },
   "platforms":[  
      {  
         "platform":"WeatherStation",
         "name":"Weather Station",
         "key":"2543ca3ae5ac26e0",
         "location":"pws:KPAMARS2",
         "forecast":"3days"
      },
      {  
         "platform":"config",
         "name":"Config",
         "port":8080,
         "log":"/var/log/daemon.log",
         "restart":"sudo systemctl restart homebridge.service",
"base": "add node_modules base path"
      }
   ]
}

**Comment by shidevil** [comment]
Refer to my readme

**Comment by dmcgrew** [comment]
Ok thanks. That worked. I still don't have a log though.. but that's because no log file exists. I'm using systemd to start homebridge on bootup. I used this guide to do it.. there's a line in the first gist to turn debugging on but that outputs to a log that also logs every other service on my pi. Do you know how to make homebridge output logs to its own log file?

**Comment by shidevil** [comment]
@dmcgrew that you have to head over to homebridge git and file a issue. As I used daemon.log. I do remember it’s possiblf

**Comment by TheSwartz** [comment]
I have this same problem.

I tried to add this:

> "base": "add node_modules base path"

Where do I find what the node_modules base path is?

Thanks!

**Comment by mkellsy** [comment]
Your global node_modules folder location depends on your OS. On a Mac it is in /usr/local/lib/node_modules. You will need to Google your OS.
