### ISSUE TITLE
Server Status Service shows HB and Console not running & Missing Uptime, CPU and Memory

### ISSUE THREAD

**Issue by ghost** [mkellsy/homebridge-config-ui#30]
![screen shot 2017-12-20 at 1 22 43 am](https://user-images.githubusercontent.com/25584103/34156991-7820ec3c-e524-11e7-99ec-7a2dd7994411.png)

Using the fork of shidevil. Everything else works fine.

My config.json as follows.
{
        "bridge": {
                "name": "HomeBridge",
                "username": "8C:B4:10:1B:6E:40",
                "port": 51826,
                "pin": "420-69-420"
        },
        "platforms": [{
                        "platform": "BelkinWeMo",
                        "name": "WeMo Platform",
                        "expected_accessories": "5",
                        "timeout": "25",
                        "no_motion_timer": "60",
                        "homekit_safe": "1"
                },
                {
                        "platform": "config",
                        "name": "Config",
                        "port": 8080,
                        "log": "/var/log/daemon.log",
                        "restart": "sudo systemctl restart homebridge.service",
                        "temp": "/sys/class/thermal/thermal_zone0/temp/",
                        "base": "/usr/local/lib/node_modules/"
                }

        ]
}

Homebridge runs on boot with systemd and configured according to [homebridge wiki](https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup-systemd).

I used mkellsy plugin first but config page wouldn't work, so I gave @shidevil  fork a try and everything else works apart from the aforementioned.

**Comment by halpls** [comment]
I removed the forward slash at the end of the paths in temp and base, now it functions.

"temp": "/sys/class/thermal/thermal_zone0/temp/",
"base": "/usr/local/lib/node_modules/"

So now they look like 

"temp": "/sys/class/thermal/thermal_zone0/temp",
"base": "/usr/local/lib/node_modules"
