### ISSUE TITLE
RPi + systemd - Can't get logs to display

### ISSUE THREAD

**Issue by Lorccan** [mkellsy/homebridge-config-ui#32]
I have tried both:

```
"log": "/var/log/daemon.log"
"log": "/var/log/syslog"
```

But still I don't see anything in the web interface.  I have checked for ad blockers etc and I don't have anything running that should affect this.

Tailing both these files shows that they have [identical?] homebridge output, so I hope this is something simple to overcome.

**Comment by Erokani** [comment]
Hi,
Got the same issue. My user homebridge was missing read rights to those files (as per default 640).
You just have to manage the access rights to those files for your homebridge user (chmod 644 e.g.).

**Comment by Lorccan** [comment]
Ah! That makes sense.  Permissions do look very restricted.  I'll report back (as I rolled-back the plugin install and will need to repeat it).

Thank you.

**Comment by Lorccan** [comment]
I'm afraid that didn't work.  I tried setting permissions to 644 on both logs [and restarting homebridge], but although everything else works, neither appears in the web UI log tab.

One difference might be that I am running homebridge under the pi user rather than a specific homebridge user, but I've not seen any other adverse effects of this.

**Comment by Erokani** [comment]
OK. I had hints on the logs, telling me about permission issues. What tell yours?

**Comment by Lorccan** [comment]
I don't see any issues anywhere in logs or in the UI. (Not sure I understand what you mean by 'hints')

**Comment by mkellsy** [comment]
Homebridge has issues with config files. The log is another one of these config files. A CHMOD 755 should do the trick. I am working on a new project that wraps around Homebridge and manages the state and configs for Homebridge. [Homebridge(X)](https://github.com/mkellsy/homebridge-x). It's not ready yet but the API works.
