### ISSUE TITLE
status page does not load?

### ISSUE THREAD

**Issue by rcfa** [mkellsy/homebridge-config-ui#33]
After installing the module, I get the following behavior:
Login page: OK
Enter user and password, hit return: nothing, page times out.
going directly to the 12.34.45.56:8080/config URL: no problem

Now I can nagivate to the other pages: plugins, users, and logs.

Trying to navigate to the status page: I get a text only page, no style applied, no graphics.

So it seems the login works, but the redirection to the status page after the login does not, nor does manually navigating to the status page work properly.

Any ideas? Bug? Configuration issue?

**Comment by Herbert-Hotz** [comment]
Same issue here!

System: Fedora 26 x86_64

**Comment by cerniuk** [comment]
Well that is annoying.  mkellsy did all this great work and it all goes to waste on some errors. Interface looks good and would be useful if whatever is at the root of the server worked.

**Comment by mkellsy** [comment]
Same as issue #34
