### ISSUE TITLE
Fails on startup with syntax error

### ISSUE THREAD

**Issue by RobotLimeLtd** [mkellsy/homebridge-config-ui#37]
When I add the systemctl config to the "platforms" section in my config.json file, I get the error below.  Interestingly, it loads the other previous modules fine, but fails on "Config", and claims the error is with line 2 of the config.json.  If I remove the code, Homebridge starts up fine.

Jun 01 13:31:19 homebridge homebridge[2912]: [2018-6-1 13:31:19] Loading 4 platforms...
Jun 01 13:31:19 homebridge homebridge[2912]: [2018-6-1 13:31:19] [Harmony Hub] Initializing HarmonyHub platform...
Jun 01 13:31:19 homebridge homebridge[2912]: [2018-6-1 13:31:19] [cmdSwitch2] Initializing cmdSwitch2 platform...
Jun 01 13:31:19 homebridge homebridge[2912]: [2018-6-1 13:31:19] [Nest] Initializing Nest platform...
Jun 01 13:31:19 homebridge homebridge[2912]: [2018-6-1 13:31:19] [Nest] Fetching Nest devices.
Jun 01 13:31:19 homebridge homebridge[2912]: [2018-6-1 13:31:19] [Config] Initializing config platform...
Jun 01 13:31:21 homebridge homebridge[2912]: /var/homebridge/config.json:2
Jun 01 13:31:21 homebridge homebridge[2912]: "bridge": {
Jun 01 13:31:21 homebridge homebridge[2912]: ^
Jun 01 13:31:21 homebridge homebridge[2912]: SyntaxError: Unexpected token :
Jun 01 13:31:21 homebridge homebridge[2912]: at createScript (vm.js:80:10)
Jun 01 13:31:21 homebridge homebridge[2912]: at Object.runInThisContext (vm.js:139:10)
Jun 01 13:31:21 homebridge homebridge[2912]: at Module._compile (module.js:588:28)
Jun 01 13:31:21 homebridge homebridge[2912]: at Object.Module._extensions..js (module.js:635:10)
Jun 01 13:31:21 homebridge homebridge[2912]: at Module.load (module.js:545:32)
Jun 01 13:31:21 homebridge homebridge[2912]: at tryModuleLoad (module.js:508:12)
Jun 01 13:31:21 homebridge homebridge[2912]: at Function.Module._load (module.js:500:3)
Jun 01 13:31:21 homebridge homebridge[2912]: at Module.require (module.js:568:17)
Jun 01 13:31:21 homebridge homebridge[2912]: at require (internal/module.js:11:18)
Jun 01 13:31:21 homebridge homebridge[2912]: at Object.<anonymous> (/usr/lib/node_modules/homebridge-config-ui/routes/index.js:7:14)
Jun 01 13:31:21 homebridge homebridge[2912]: at Module._compile (module.js:624:30)
Jun 01 13:31:21 homebridge homebridge[2912]: at Object.Module._extensions..js (module.js:635:10)
Jun 01 13:31:21 homebridge homebridge[2912]: at Module.load (module.js:545:32)
Jun 01 13:31:21 homebridge homebridge[2912]: at tryModuleLoad (module.js:508:12)
Jun 01 13:31:21 homebridge homebridge[2912]: at Function.Module._load (module.js:500:3)
Jun 01 13:31:21 homebridge homebridge[2912]: at Module.require (module.js:568:17)
Jun 01 13:31:21 homebridge homebridge[2912]: at require (internal/module.js:11:18)
Jun 01 13:31:21 homebridge homebridge[2912]: at Object.<anonymous> (/usr/lib/node_modules/homebridge-config-ui/app.js:68:13)
Jun 01 13:31:21 homebridge homebridge[2912]: at Module._compile (module.js:624:30)
Jun 01 13:31:21 homebridge homebridge[2912]: at Object.Module._extensions..js (module.js:635:10)
Jun 01 13:31:21 homebridge homebridge[2912]: at Module.load (module.js:545:32)
Jun 01 13:31:21 homebridge homebridge[2912]: at tryModuleLoad (module.js:508:12)
Jun 01 13:31:21 homebridge homebridge[2912]: at Function.Module._load (module.js:500:3)
Jun 01 13:31:21 homebridge homebridge[2912]: at Module.require (module.js:568:17)
Jun 01 13:31:21 homebridge homebridge[2912]: at require (internal/module.js:11:18)
Jun 01 13:31:21 homebridge homebridge[2912]: at new HttpServer (/usr/lib/node_modules/homebridge-config-ui/index.js:46:15)
Jun 01 13:31:21 homebridge homebridge[2912]: at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:294:32)
Jun 01 13:31:21 homebridge homebridge[2912]: at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:80:36)
Jun 01 13:31:21 homebridge systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Jun 01 13:31:21 homebridge systemd[1]: Unit homebridge.service entered failed state.

**Comment by Tobix99** [comment]
Can you post your config please? Maybe it has something to do with other plugins?

**Comment by mkellsy** [comment]
It looks like your config is corrupt. Paste your config file contents into this site https://jsonlint.com/. It will tell you what is wrong.
