### ISSUE TITLE
Scan Code - Camera Iphone

### ISSUE THREAD

**Issue by fmoreni** [mkellsy/homebridge-config-ui#39]
Hello, Great work.

Does the code scan not seem to work? I'm using the iphone camera to scannear.

Is it necessary any more, module to work?

Thanks for the tip.

**Comment by seanip** [comment]
Check out my profile picture see if it works for you

**Comment by mkellsy** [comment]
I was able to scan the code. This is an issue with the phones camera and the monitor. The new version of homebridge displays a setup qrcode that works better. I am working on a new homebridge stack that shows this qrcode. I will not be adding it to this interface.
