### ISSUE TITLE
I must install supervisor for running that ?

### ISSUE THREAD

**Issue by Juanillo62gm** [mkellsy/homebridge-config-ui#4]
I have installed the plugin on my raspberry pi zero w and follow the instructions but I don't know how to run the server.

**Comment by mkellsy** [comment]
I use supervisor to keep Homebridge alive. It is like launchd but more flexible. To view the log you need to log Homebeidge’s output to a file. The restart command can be anything.

**Comment by mkellsy** [comment]
This starts with Homebridge. Homebridge’s RegisterPlugin function will start a HTTP server for this.

**Comment by mkellsy** [comment]
You can use systemctl instead of supervisor. The guys over at Homebridge have a how to for that https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi

Then you can change the restart command to systemctl restart homebridge.
