### ISSUE TITLE
Help Not working

### ISSUE THREAD

**Issue by intentionstore** [mkellsy/homebridge-config-ui#40]
After I visit http://localhost:8080/
![screenshot 2018-10-03 at 18 22 01](https://user-images.githubusercontent.com/34816191/46427507-84ceaa80-c739-11e8-8302-f89fdccc747e.png)

My config:

{
  "bridge": {
    "name": "Homebridge Hub",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },

  "platforms": [
    {
    "platform": "config",
    "name": "Config",
    "port": 8080,
    "log": "/var/log/homebridge.stdout.log",
    "error_log": "/var/log/homebridge.stderr.log",
    "restart": "/usr/local/bin/supervisorctl restart homebridge"
    }
 ],
  "accessories": [
  ]
}

**Comment by ahnyerkeester** [comment]
It didn't work for me at first. Then I remembered that when I set up Homebridge to run on boot I had to copy 'config.json' to another folder. So updating '/home/pi/.homebridge/config.json' didn't really affect it. I had to 'sudo cp ~/.homebridge/config.json /var/homebridge/' again to get it to work. Restarted Homebridge and it works! Hope that helps.
