### ISSUE TITLE
Command console with Dashboard

### ISSUE THREAD

**Issue by Nastras** [mkellsy/homebridge-config-ui#7]
Hello,
Nice plugin you have there. Thank you for your work!

I have another idea for a future version of your plugin, which I would like to share with you.

Is it possible to include a command console with a dashboard.
In the dashboard individual commands can be created in the config?

Similar to your switch for restart.

I hope you understand what i mean?

**Comment by mkellsy** [comment]
There is a Homebridge plug-ins for that. https://github.com/luisiam/homebridge-cmdswitch2

**Comment by Nastra888** [comment]
Thanks for the tip, but I do not mean. I do not want to give commands with a switch in HomeKit consoles. I mean a kind of toolbox with favorites for editing the homebridge in a console without entering again and again.

Look here, I have collected a lot of commands for editing a homebridge. http://forum.smartapfel.de/forum/thread/101-homebridge-befehlssammlung/

If you build a console with favorite switch where you could store these commands that would be awesome.

It is possible and understandable what I mean

**Comment by Nastra888** [comment]
It would be great to fit your plugin.

**Comment by mkellsy** [comment]
I see what you are talking about. Thanks for the input. I will look into this.

**Comment by Nastra888** [comment]
Cool, would be really happy if you would install.
Makes working on the homebridge much easier.

Greeting Nastra
