### ISSUE TITLE
Add language support

### ISSUE THREAD

**Issue by mkellsy** [mkellsy/homebridge-config-ui#8]
homebridge-config-ui has gone international, thanks [Krocko](https://github.com/Krocko)

I will use Krocko German translations.

**Comment by Krocko** [comment]
OHHHH COOOOL

**Comment by gerritfries** [comment]
Is it already possible to use those translations? Do I have to change some files or how does it work? By the way: Thank you so much for this great plugin! It's a huge timesaver when it comes to change or add plugin configs. And the look and feel is really nice too!

**Comment by mkellsy** [comment]
This is an enhancement (feature request) I will need to write code to get the local system working. For now the code only supports English.
