### ISSUE TITLE
systemd

### ISSUE THREAD

**Issue by ageorgios** [mkellsy/homebridge-config-ui#9]
looks great, not tested though since it does not work with systemd :(

**Comment by shidevil** [comment]
It does work with systemd as I'm running homebridge with systemd bootup

**Comment by shidevil** [comment]
My config file looks like this. Works perfectly and logs as shown.

`{
    "platform": "config",
    "name": "Config",
    "port": 8080,
    "log": "/var/log/daemon.log",
    "restart": "sudo systemctl restart homebridge.service"
}`

**Comment by ageorgios** [comment]
ok thanx ill try the config!

**Comment by shidevil** [comment]
Is the log stored at var/log/daemon.log?

Or yours is store at var/log/syslog?

**Comment by ageorgios** [comment]
homebridge-config-ui@1.1.2
Chrome 59.0.3071.115 

log pointing on /var/log/syslog

**Comment by shidevil** [comment]
Try changing "log": to var/log/syslog?

**Comment by ageorgios** [comment]
This is the config file:
```
    {
      "platform": "config",
      "name": "Config",
      "port": 8080,
      "log": "/var/log/syslog",
      "restart": "sudo systemctl restart homebridge.service"
    },
```

**Comment by mkellsy** [comment]
Shidevil updated the readme file with instructions for systemd installs.

**Comment by shidevil** [comment]
@ageorgios i personally tried /var/log/syslog and its working fine for Chrome and Safari.

**Comment by shidevil** [comment]
@ageorgios you may have Adblock on that is preventing the logs from showing. Please turn off  adblock

**Comment by ageorgios** [comment]
oh god so stupid... I'll try and tell
